---
data:
  train:
    paths:
      - "egs/yahoo_answer/text_cls/v1/data/train.small.txt"
  eval:
    paths:
      - "egs/yahoo_answer/text_cls/v1/data/dev.small.txt"
  infer:
    paths:
      - "egs/yahoo_answer/text_cls/v1/data/test.small.txt"
  task:
    name: TextClsTask
    preparer:
      enable: true
      name: TextClsPreparer
      done_sign: "egs/yahoo_answer/text_cls/v1/exp/prepare.done"
      reuse: true
    use_dense: false
    language: english
    vocab_min_frequency: 20
    text_vocab: "egs/yahoo_answer/text_cls/v1/exp/text_vocab.txt"
    label_vocab: "egs/yahoo_answer/text_cls/v1/exp/label_vocab.txt"
    max_seq_len: 1024
    num_parallel_calls: 12
    num_prefetch_batch: 2
    shuffle_buffer_size: 15000
    need_shuffle: true
    batch_size: 32
    epochs: 100
    classes:
      positive_id: 1
      num_classes: 10
      vocab:
        0: 0
        1: 1
        2: 2
        3: 3
        4: 4
        5: 5
        6: 6
        7: 7
        8: 8
        9: 9

model:
  name: HierarchicalAttentionModel
  type: keras
  use_pre_train_emb: false
  pre_train_emb_path: ""
  embedding_path: "egs/yahoo_answer/text_cls/v1/exp/embeding.pkl"

  net:
    structure:
      embedding_size: 200
      emb_trainable: true
      cell_type: gru
      cell_dim: 100
      num_layers: 1
      max_len: 1024
      max_sen_len: 32
      max_doc_len: 32
      dropout_rate: 0.5
      l2_reg_lambda: 0

solver:
  name: RawClassSolver
  quantization:
    enable: false # whether to quantization model
    quant_delay: 0 # Number of steps after which weights and activations are quantized during training
  adversarial:
    enable: false # whether to using adversiral training
    adv_alpha: 0.5 # adviseral alpha of loss
    adv_epslion: 0.1 # adviseral example epslion
  model_average:
    enable: false # use average model
    var_avg_decay: 0.99 # the decay rate of varaibles
  optimizer:
    name: adam
    loss: CrossEntropyLoss 
    label_smoothing: 0.0 # label smoothing rate
    learning_rate:
      rate: 0.0001 # learning rate of Adam optimizer
      type:  exp_decay # learning rate type
      decay_rate: 0.99  # the lr decay rate
      decay_steps: 100  # the lr decay_step for optimizer
    clip_global_norm: 3.0 # clip global norm
    multitask: False # whether is multi-task
  metrics:
    pos_label: 1 # int, same to sklearn
    cals:
      - name: AccuracyCal
        arguments: Null
      - name: PrecisionCal
        arguments:
          average: 'macro'
      - name: RecallCal
        arguments:
          average: 'macro'
      - name: F1ScoreCal
        arguments:
          average: 'weighted'
  postproc:
    name: SavePredPostProc
    res_file: ""
  saver:
    model_path: "egs/yahoo_answer/text_cls/v1/exp/han-cls/ckpt"
    max_to_keep: 30
    save_checkpoint_steps: 100
    print_every: 10
  service:
    model_path: "egs/yahoo_answer/text_cls/v1/exp/han-cls/service"
    model_version: "1"
  run_config:
    tf_random_seed: null
    allow_soft_placement: true
    log_device_placement: false
    intra_op_parallelism_threads: 10
    inter_op_parallelism_threads: 10
    allow_growth: true
