---
# han in mock data set
data:
  train:
    paths:
      - "./delta/config/data/text_cls/english/mock_train"
  eval:
    paths:
      - "./delta/config/data/text_cls/english/mock_dev"
  infer:
    paths:
      - "./delta/config/data/text_cls/english/mock_test"
    res: ckpt/han-cls/res/infer.txt
  task:
    name: TextClsTask
    use_dense: false
    language: english
    vocab_min_frequency: 20
    text_vocab: ckpt/han-cls/data/text_vocab.txt
    label_vocab: ckpt/han-cls/data/label_vocab.txt
    max_seq_len: 1024
    batch_size: 32
    epochs: 1
    num_parallel_calls: 12
    num_prefetch_batch: 2
    shuffle_buffer_size: 1000
    need_shuffle: true
    classes:
      positive_id: 1
      num_classes: 2
      vocab:
        negative: 0
        positive: 1

model:
  name: HierarchicalAttentionModel
  type: keras  # raw, keras or eager model
  use_pre_train_emb: false
  pre_train_emb_path: ""
  embedding_path: ckpt/han-cls/data/embeding.pkl
  net:
    structure:
      embedding_size: 200
      emb_trainable: true
      cell_type: gru # gru/lstm/cudnngru/cudnnlstm
      cell_dim: 100
      num_layers: 1
      max_len: 1024
      max_sen_len: 32
      max_doc_len: 32
      dropout_rate: 0.5
      l2_reg_lambda: 0

solver:
  name: RawSolver
  quantization:
    enable: false # whether to quantization model
    quant_delay: 0 # Number of steps after which weights and activations are quantized during training
  adversarial:
    enable: false # whether to using adversiral training
    adv_alpha: 0.5 # adviseral alpha of loss
    adv_epslion: 0.1 # adviseral example epslion
  model_average:
    enable: false # use average model
    var_avg_decay: 0.99 # the decay rate of varaibles
  optimizer:
    name: rmsprop
    loss: CrossEntropyLoss
    label_smoothing: 0.0 # label smoothing rate
    learning_rate:
      rate: 0.001 # learning rate of Adam optimizer
      type:  exp_decay # learning rate type
      decay_rate: 0.99  # the lr decay rate
      decay_steps: 100  # the lr decay_step for optimizer
    clip_global_norm: 3.0 # clip global norm
    multitask: False # whether is multi-task
  metrics:
    pos_label: 1 # int, same to sklearn
    cals:
      - name: AccuracyCal
        arguments: Null
      - name: PrecisionCal
        arguments:
          average: 'macro'
      - name: RecallCal
        arguments:
          average: 'macro'
      - name: F1ScoreCal
        arguments:
          average: 'weighted'
    keras:
      - name: acc
  saver:
    model_path: "ckpt/han-cls"
    max_to_keep: 10
    save_checkpoint_steps: 31 # the step to save checkpoint
    summary: false
    print_every: 10
    resume_model_path: ""
  service:
    model_path: ckpt/han-cls/saved_model
    pb_path: ckpt/han-cls/pb/freezed.pb
    model_version: "1"
  run_config:
    tf_random_seed: null
    allow_soft_placement: true
    log_device_placement: false
    intra_op_parallelism_threads: 10
    inter_op_parallelism_threads: 10
    allow_growth: true
