---
data:
  train:
    paths:
      - "config/data/mock_train"
  dev:
    paths:
      - "config/data/mock_dev"
  eval:
    paths:
      - "config/data/mock_test"
  task:
    name: TextClsTask
    keyword: ckpt/rnn-cls/example/keyword_list
    vocab_min_frequency: 20
    text_vocab: ckpt/rnn-cls/example/text_vocab.pkl
    label_vocab: ckpt/rnn-cls/example/label_vocab.pkl
    max_seq_len: 1024
    num_classes: 4
    batch_size: 32
    epochs: 2
    num_parallel_calls: 12
    num_prefetch_batch: 2
    shuffle_buffer_size: 200000
    need_shuffle: true
    classes:
      positive_id: 1
      vocab:
        0: 0
        1: 1
        2: 2
        3: 3

model:
  name: RnnAttentionModel
  type: keras # raw, keras or eager model
  use_pre_train_emb: true
  pre_train_emb_path: /nfs/project/han_new/all_data/data_w2v/w2v_char.txt
  embedding_path: ckpt/rnn-cls/example/embeding.pkl
  net:
    structure:
      embedding_size: 200
      cell_type: lstm
      cell_dim: 100
      num_layers: 1
      batch_size: 32
      max_len: 1024
      dropout_rate: 0.5
      l2_reg_lambda: 0

solver:
  name: RawSolver
  quantization:
    enable: false # whether to quantization model
    quant_delay: 0 # Number of steps after which weights and activations are quantized during training
  adversarial:
    enable: false # whether to using adversiral training
    adv_alpha: 0.5 # adviseral alpha of loss
    adv_epslion: 0.1 # adviseral example epslion
  model_average:
    enable: false # use average model
    var_avg_decay: 0.99 # the decay rate of varaibles
  optimizer:
    name: adam
    loss: CrossEntropyLoss 
    label_smoothing: 0.0 # label smoothing rate
    learning_rate:
      rate: 0.0001 # learning rate of Adam optimizer
      type:  exp_decay # learning rate type
      decay_rate: 0.99  # the lr decay rate
      decay_steps: 100  # the lr decay_step for optimizer
    batch_size: 32
    epochs: 3
    clip_global_norm: 3.0 # clip global norm
    multitask: False # whether is multi-task
  metrics:
    pos_label: 1 # int, same to sklearn
    cals:
      - name: AccuracyCal
        arguments: Null
      - name: PrecisionCal
        arguments:
          average: 'macro'
      - name: RecallCal
        arguments:
          average: 'macro'
      - name: F1ScoreCal
        arguments:
          average: 'weighted'
  saver:
    model_path: "ckpt/rnn-cls/1"
    max_to_keep: 10
    save_checkpoints_steps: 100
    keep_checkpoint_every_n_hours: 10000
    checkpoint_every: 10 # the step to save checkpoint
    summary: false
    save_summary_steps: 100
    eval_on_dev_every_secs: 1
    print_every: 10
    resume_model_path: "mock/rnn-cls/checkpoints/model/model.ckpt-10"
  service:
    model_path: "mock/rnn-cls/service"
    model_version: "1"
  run_config:
    tf_random_seed: null
    allow_soft_placement: true
    log_device_placement: false
    intra_op_parallelism_threads: 10
    inter_op_parallelism_threads: 10
    allow_growth: true
