---
data:
  train:
    paths:
      - "egs/inner_kc/nlp1/data/kc.train_0315.shuf.std"
  eval:
    paths:
      - "egs/inner_kc/nlp1/data/kc.test_0315.shuf.std"
  infer:
    paths:
      - "egs/inner_kc/nlp1/data/kc.test_0315.shuf.std"
  task:
    name: TextClsTask
    prepare:
      enable: true
      name: TextClsPreparer
      done_sign: "egs/mock_text_cls_data/nlp1/exp/prepare.done"
      reuse: true
    use_dense: false
    language: chinese
    split_by_space: true
    vocab_min_frequency: 20
    text_vocab: "egs/inner_kc/nlp1/exp/text_vocab.txt"
    label_vocab: "egs/inner_kc/nlp1/exp/label_vocab.txt"
    max_seq_len: 1024
    num_parallel_calls: 12
    num_prefetch_batch: 2
    shuffle_buffer_size: 30000
    need_shuffle: true
    batch_size: 32
    epochs: 15
    classes:
      positive_id: 1
      num_classes: 4
      vocab:
        0: 0
        1: 1
        2: 2
        3: 3

model:
  name: TransformerModel
  type: keras
  use_pre_train_emb: false
  pre_train_emb_path: ""
  embedding_path: "egs/inner_kc/nlp1/exp/embeding.pkl"
  net:
    structure:
      embedding_size: 200
      emb_trainable: true
      num_layers: 4
      max_len: 1024
      dropout_rate: 0.2
      l2_reg_lambda: 0
      transformer_dropout: 0.1
      residual_conn: true
      head_num: 8
      hidden_dim: 256

solver:
  name: RawSolver
  quantization:
    enable: false # whether to quantization model
    quant_delay: 0 # Number of steps after which weights and activations are quantized during training
  adversarial:
    enable: false # whether to using adversiral training
    adv_alpha: 0.5 # adviseral alpha of loss
    adv_epslion: 0.1 # adviseral example epslion
  model_average:
    enable: false # use average model
    var_avg_decay: 0.99 # the decay rate of varaibles
  optimizer:
    name: adam
    loss: CrossEntropyLoss
    label_smoothing: 0.0 # label smoothing rate
    learning_rate:
      rate: 0.0005 # learning rate of Adam optimizer
      type:  exp_decay # learning rate type
      decay_rate: 0.99  # the lr decay rate
      decay_steps: 100  # the lr decay_step for optimizer
    clip_global_norm: 3.0 # clip global norm
    multitask: False # whether is multi-task
    batch_size: 32
    epochs: 15
  metrics:
    pos_label: 1 # int, same to sklearn
    cals:
      - name: AccuracyCal
        arguments: Null
      - name: PrecisionCal
        arguments:
          average: 'macro'
      - name: RecallCal
        arguments:
          average: 'macro'
      - name: F1ScoreCal
        arguments:
          average: 'weighted'
  saver:
    model_path: "egs/inner_kc/nlp1/exp/transformer-cls/ckpt"
    max_to_keep: 30
    save_checkpoint_steps: 100
    print_every: 10
  service:
    model_path: "egs/inner_kc/nlp1/exp/transformer-cls/service"
    model_version: "1"
  run_config:
    tf_random_seed: null
    allow_soft_placement: true
    log_device_placement: false
    intra_op_parallelism_threads: 10
    inter_op_parallelism_threads: 10
    allow_growth: true
